[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
    [plugins.inputs]
    enableMatcher = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
